# Generated by Django 5.0.4 on 2024-10-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='sex',
            field=models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1),
        ),
    ]
