# Generated by Django 5.0.4 on 2024-10-13 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_alter_patientcardmainpart_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес постоянной (временной) регистрации'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='birth_date',
            field=models.DateField(verbose_name='Число, месяц, год рождения'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+375XX XXX XX XX'.", regex='^\\+375\\d{2}\\d{7}$')], verbose_name='Номер контактного телефона'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='place_of_work',
            field=models.CharField(max_length=100, null=True, verbose_name='Место работы (службы, учебы)'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='sex',
            field=models.CharField(choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='social_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Социальное положение'),
        ),
        migrations.AlterField(
            model_name='patientcardmainpart',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
