# Generated by Django 5.0.4 on 2024-10-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_alter_patientcardmainpart_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCardXRayPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_research', models.CharField(max_length=50, verbose_name='Назначен вид исследования')),
                ('prescribed_doctor', models.CharField(choices=[('КОП', 'К.О.П.'), ('ИИИ', 'И.И.И.')], max_length=50, verbose_name='Назначил (врач)')),
                ('research_conducted', models.CharField(max_length=50, verbose_name='Проведено исследование (организация)')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('equivalent_dose', models.FloatField(verbose_name='Эквивалентная доза(мЗВ)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_appointments', to='doctor_app.patientcardmainpart')),
            ],
        ),
    ]
