# Generated by Django 5.0.4 on 2024-10-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_patientcardxraypart'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitsDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Дата, жалобы, клиническая картина, результаты исследований, диагноз, план лечения, лечение')),
                ('prescribed_doctor', models.CharField(choices=[('КОП', 'К.О.П.'), ('ИИИ', 'И.И.И.')], max_length=50, verbose_name='Фамилия, имя, отчество врача')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_diary', to='doctor_app.patientcardmainpart')),
            ],
        ),
    ]
