# Generated by Django 5.0.4 on 2024-10-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_visitsdiary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientcardmainpart',
            options={'verbose_name_plural': 'Cтоматологическая амбулаторная карта'},
        ),
        migrations.AlterModelOptions(
            name='patientcardxraypart',
            options={'verbose_name_plural': 'Лист назначений и учета нагрузок рентгенологических исследований'},
        ),
        migrations.AlterModelOptions(
            name='visitsdiary',
            options={'verbose_name_plural': 'Дневник посещений'},
        ),
    ]
